public enum ItemName
{
    NONE = -1,
    FOOD_APPLE,
    FOOD_CHICKEN,
    WATER_WATER,
    RESOURCE_ROCK,
    RESOURCE_WOOD,
    RESOURCE_IRON,
    FOOD_POTATO,
    FOOD_POTATO_WITH_CHICKEN,
    ARMOR_SIMPLE_IRON_CUIRASS,
    WEAPON_MAKAR_PISTOL,
    WEAPON_AK47,
    GRENADE_BASIC_FRAG
}
