public enum ItemName
{
    //FOOD
    FOOD_APPLE,
    FOOD_CHICKEN,
    WATER_WATER,
    RESOURCE_ROCK,
    RESOURCE_WOOD,
    RESOURCE_IRON,
    FOOD_POTATO,
    FOOD_POTATO_WITH_CHICKEN,
    ITEM_SKILLET,
    RECIPE_POTATO_CHICKEN,
    WEAPON_AXE
}
